VoiceSage.Web/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VoiceSage.Web.Models;
using VoiceSage.Web.Services;
using VoiceSage.Web.Services.IServices;

namespace VoiceSage.Web.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;
        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        public async Task<IActionResult> ContactIndex()
        {
            List<ContactDto> list = new List<ContactDto>();
            var response = await _contactService.GetAllContactsAsync<ResponseDto>();

            if (response != null && response.IsSucess)
                list = JsonConvert.DeserializeObject<List<ContactDto>>(Convert.ToString(response.Result));
            return View(list);
        }

        public async Task<IActionResult> ContactCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ContactCreate(ContactDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _contactService.CreateContactAsync<ResponseDto>(model);
                if (response != null && response.IsSucess)
                    return RedirectToAction(nameof(ContactIndex));
            }
            return View(model);
        }

        public async Task<IActionResult> AddRemoveGroup([FromServices] IGroupService groupService, int contactId, int groupId)
        {
            var response = await _contactService.GetContactByIdAsync<ResponseDto>(contactId);
            if (response != null && response.IsSucess)
            {
                ContactDto model = JsonConvert.DeserializeObject<ContactDto>(Convert.ToString(response.Result));
                ContactGroupDto cgDto = new ContactGroupDto
                {
                    ContactId = contactId,
                    GroupId = groupId
                };
                if (model.ContactGroups.Where(x => x.ContactId == contactId)
                    .Where(x => x.GroupId == groupId).FirstOrDefault() != null) {
                    var l = model.ContactGroups.ToList();
                    l.RemoveAll(x => x.GroupId == groupId);
                    model.ContactGroups = l;
                }
                else
                    model.ContactGroups.Add(cgDto);
                var updateResponse = await _contactService.UpdateContactAsync<ResponseDto>(model);
                List<GroupDto> list = new List<GroupDto>();
                
                return RedirectToAction(nameof(ContactEdit), new { contactId = model.ContactId});
            }
            return NotFound();
        }

        public async Task<IActionResult> ContactEdit([FromServices] IGroupService groupService, int contactId)
        {
            var response = await _contactService.GetContactByIdAsync<ResponseDto>(contactId);
            if (response != null && response.IsSucess)
            {
                ContactDto model = JsonConvert.DeserializeObject<ContactDto>(Convert.ToString(response.Result));
                List<GroupDto> list = new List<GroupDto>();
                var groupsResponse = await groupService.GetAllGroupsAsync<ResponseDto>();

                if (groupsResponse != null && response.IsSucess)
                    list = JsonConvert.DeserializeObject<List<GroupDto>>(Convert.ToString(groupsResponse.Result));
                ViewBag.AllGroups = model.ContactGroups.ToList();
                ViewModelContact viewModel = new ViewModelContact
                {
                    ContactDto = model,
                    Groups = list.ToList()

                };
                return View(viewModel);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ContactEdit(ViewModelContact model)
        {
            var response = await _contactService.GetContactByIdAsync<ResponseDto>(model.ContactDto.ContactId);
            if (response != null && response.IsSucess)
            {
                ContactDto modelR = JsonConvert.DeserializeObject<ContactDto>(Convert.ToString(response.Result));
                if (ModelState.IsValid)
                {
                    model.ContactDto.ContactGroups = modelR.ContactGroups;
                    var responseR = await _contactService.UpdateContactAsync<ResponseDto>(model.ContactDto);
                    if (responseR != null && responseR.IsSucess)
                        return RedirectToAction(nameof(ContactIndex));
                }
                return View(model.ContactDto);
            }
            return NotFound();
        }

        public async Task<IActionResult> ContactDelete(int contactId)
        {
            var response = await _contactService.GetContactByIdAsync<ResponseDto>(contactId);
            if (response != null && response.IsSucess)
            {
                ContactDto model = JsonConvert.DeserializeObject<ContactDto>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ContactDelete(ContactDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _contactService.DeleteContactAsync<ResponseDto>(model.ContactId);
                if (response.IsSucess)
                    return RedirectToAction(nameof(ContactIndex));
            }
            return View(model);
        }

       /*
        public async Task<IActionResult> GroupSelect([FromServices] IGroupService groupService, ContactDto model)
        {
            List<GroupDto> list = new List<GroupDto>();
            var response = await groupService.GetAllGroupsAsync<ResponseDto>();

            if (response != null && response.IsSucess)
                list = JsonConvert.DeserializeObject<List<GroupDto>>(Convert.ToString(response.Result));

            ViewModelContact viewModelContact = new ViewModelContact();
            viewModelContact.ContactDto = model;
            viewModelContact.Groups = list;
            return View(viewModelContact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GroupSelect(ContactDto model)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(ContactEdit));
            }
            return View(model);
        }*/
    }
}

VoiceSage.Web/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VoiceSage.Web.Models;
using VoiceSage.Web.Services.IServices;

namespace VoiceSage.Web.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupService _groupService;
        public GroupController(IGroupService groupervice)
        {
            _groupService = groupervice;
        }

        public async Task<IActionResult> GroupIndex()
        {
            List<GroupDto> list = new List<GroupDto>();
            var response = await _groupService.GetAllGroupsAsync<ResponseDto>();

            if (response != null && response.IsSucess)
                list = JsonConvert.DeserializeObject<List<GroupDto>>(Convert.ToString(response.Result));
            return View(list);
        }

        public async Task<IActionResult> GroupCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GroupCreate(GroupDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _groupService.CreateGroupAsync<ResponseDto>(model);
                if (response != null && response.IsSucess)
                    return RedirectToAction(nameof(GroupIndex));
            }
            return View(model);
        }

        public async Task<IActionResult> GroupEdit(int groupId)
        {
            var response = await _groupService.GetGroupByIdAsync<ResponseDto>(groupId);
            if (response != null && response.IsSucess)
            {
                GroupDto model = JsonConvert.DeserializeObject<GroupDto>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GroupEdit(GroupDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _groupService.UpdateGroupAsync<ResponseDto>(model);
                if (response != null && response.IsSucess)
                    return RedirectToAction(nameof(GroupIndex));
            }
            return View(model);
        }

        public async Task<IActionResult> GroupDelete(int groupId)
        {
            var response = await _groupService.GetGroupByIdAsync<ResponseDto>(groupId);
            if (response != null && response.IsSucess)
            {
                GroupDto model = JsonConvert.DeserializeObject<GroupDto>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GroupDelete(GroupDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _groupService.DeleteGroupAsync<ResponseDto>(model.GroupId);
                if (response.IsSucess)
                    return RedirectToAction(nameof(GroupIndex));
            }
            return View(model);
        }
    }
}

VoiceSage.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VoiceSage.Web</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img width="75px" src="/images/logo.svg"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="ContactIndex">Contacts</a>
                        </li>
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link" asp-area="" asp-controller="Group" asp-action="GroupIndex">Groups</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - VoiceSage.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>